services:
  backend:
    build: .
    image: backend-image
    container_name: backend
    restart: unless-stopped
    env_file: .env
    environment:
      - WEB_CONCURRENCY
    ports:
      - "8000:8000"