name: Qseer application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Fetch latest commit
      uses: actions/checkout@v4
    - name: Build app
      run: docker compose up --force-recreate --build --detach
